# If metrics server is enabled, you can apply "enabled: true", by this setting application will be automatically scales based on the cpu and memory threshold

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# If autoscaling is not enabled you should increase the replica counts on weekends.
replicaCount: 3

image:
  repository: atamq/mb
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  exposedPort: 30080 # Port must be in the 30000-32767 range
  port: 8080

namespace: default

# Sensitive environment variables, must be set when deploying 
license: shouldSet
name: shouldSet

healthReady:
  initialDelaySeconds: 60
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

healthLive:
  initialDelaySeconds: 60
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3