apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app-infra.fullname" . }}
  labels:
    {{- include "sample-app-infra.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: http-svc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.exposedPort }}
  selector:
    {{- include "sample-app-infra.selectorLabels" . | nindent 4 }}
